-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `projetophp` DEFAULT CHARACTER SET utf8 ;
USE `projetophp` ;

CREATE TABLE IF NOT EXISTS `projetophp`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `senha` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS 'projetophp'.'cliente'(
    'id' INT NOT NULL AUTO_INCREMENT,
    'nome' VARCHAR(255) NOT NULL,
    'cpf' VARCHAR(255) NOT NULL,
    PRIMARY KEY ('id')
ENGINE = InnoDB
)

CREATE TABLE IF NOT EXISTS 'projetophp'.'servico'(
    'id' INT NOT NULL AUTO_INCREMENT,
    'descricao' VARCHAR(255) NOT NULL,
    PRIMARY KEY ('id')
ENGINE = InnoDB
)

CREATE TABLE IF NOT EXISTS 'projetophp'.'itens'(
    'id' INT NOT NULL AUTO_INCREMENT,
    'descricao' VARCHAR(255) NOT NULL,
    PRIMARY KEY ('id')
ENGINE = InnoDB

)